from xml.sax.handler import property_interning_dict

print(" ")
# print("hello world!")
# print("hello again")
# print("i like typing this.")
# print("this is fun.")
# print('yay! printing.')
# print("i`d much rather you 'not'.")
# print('i "said" do not touch this')
print(" ")
print("============================")
print(" ")
print("hello everyone")
print("i'm printing right now")
print("yup, just printing")
print(" ")